# Generated by Django 5.1.1 on 2025-01-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг'},
        ),
    ]
